'use client';
import { useCallback, useEffect, useRef, useState, type FormEvent, type ReactNode, type CSSProperties } from 'react';
import { Activity, ArrowDownToLine, ArrowRight, CalendarDays, Check, ChevronLeft, ChevronRight, CircleHelp, Clock3, Copy, Gamepad2, GraduationCap, LayoutDashboard, LogOut, Monitor, Plus, RefreshCw, ShieldCheck, Smartphone, Sparkles, Trash2, WifiOff, X } from 'lucide-react';
import type { DashboardData, DaySnapshot, Device, Usage } from '@/lib/schema';
import { activities, categoryColor, clock, combine, dateLabel, dayRange, duration, shiftDay } from '@/lib/data';

type View='overview'|'history'|'devices';
type User={email:string};
async function api<T>(path:string,method='GET',body?:unknown):Promise<T>{
  const res=await fetch(path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});
  const data=await res.json();if(!res.ok)throw new Error(data.error??'Не удалось связаться с кабинетом.');return data;
}
function Brand(){return <div className="brand"><span className="brand-symbol"><Clock3 size={23}/></span><span>family<span className="brand-light">time</span><small>Время для важного</small></span></div>;}
function Help({text}:{text:string}){return <span className="help" tabIndex={0} aria-label={text}><CircleHelp size={15}/><span role="tooltip">{text}</span></span>;}
function Empty({title,children,icon=<Activity size={30}/>}:{title:string;children:ReactNode;icon?:ReactNode}){return <div className="empty"><span className="empty-icon">{icon}</span><h3>{title}</h3><div>{children}</div></div>;}
function ErrorBox({text}:{text:string}){return text?<div className="error" role="alert">{text}</div>:null;}
function stamp(value:string|null,zone='Europe/Moscow'){return value?new Intl.DateTimeFormat('ru',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:zone}).format(new Date(value)):'Ещё не было';}
function online(device:Device){return !!device.last_seen_at&&Date.now()-Date.parse(device.last_seen_at)<180_000;}
function Status({device}:{device:Device}){return <span className={'status '+(online(device)?'online':'offline')}><span/>{online(device)?device.metadata.paused?'Учёт на паузе':'На связи':'Нет связи'}</span>;}

function Auth({onLogin,passwordMode=false}:{onLogin:()=>void;passwordMode?:boolean}){
  const [mode,setMode]=useState(passwordMode?'password':'sign-in');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
  useEffect(()=>{if(new URLSearchParams(location.search).has('authError'))setError('Ссылка недействительна или истекла. Запросите новое письмо.');},[]);
  function choose(next:string){setMode(next);setError('');setMessage('');}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setMessage('');const form=new FormData(e.currentTarget);
    try{const result=await api<{ok?:boolean;message?:string}>('/api/auth','POST',{action:mode,email:form.get('email'),password:form.get('password')});if(result.ok){history.replaceState(null,'','/');onLogin();}else setMessage(result.message??'Готово.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const title=mode==='sign-up'?'Всё важное — рядом':mode==='reset'?'Вернём доступ':mode==='password'?'Новый пароль':'Рады видеть вас';
  return <div className="auth-shell"><aside className="auth-story"><Brand/><div className="story-content"><span className="eyebrow">СПОКОЙСТВИЕ ВМЕСТО ДОГАДОК</span><h1>Больше понимания.<br/><em>Больше баланса.</em></h1><p>Знайте, как проходит время за компьютером.<br/>Даже когда вы далеко друг от друга.</p><div className="story-art" aria-hidden="true"><div className="orbit one"/><div className="orbit two"/><div className="art-clock"><Clock3 size={84} strokeWidth={1.2}/></div><span className="float-badge study"><GraduationCap size={22}/> Время учиться</span><span className="float-badge play"><Gamepad2 size={22}/> Время играть</span><span className="float-badge family"><Sparkles size={22}/> Время быть вместе</span></div></div><div className="story-bottom"><ShieldCheck size={17}/> История доступна только вашей семье</div></aside><main className="auth-main"><div className="mobile-brand"><Brand/></div><div className="auth-card"><span className="eyebrow">ЛИЧНЫЙ КАБИНЕТ</span><h2>{title}</h2><p className="muted">{mode==='sign-up'?'Создайте аккаунт, чтобы видеть историю на любом устройстве.':mode==='reset'?'Отправим ссылку для смены пароля на вашу почту.':mode==='password'?'Придумайте пароль от 8 символов.':'Войдите, чтобы узнать, как прошёл день.'}</p>{!['reset','password'].includes(mode)&&<div className="segmented auth-tabs"><button type="button" className={mode==='sign-in'?'selected':''} onClick={()=>choose('sign-in')}>Войти</button><button type="button" className={mode==='sign-up'?'selected':''} onClick={()=>choose('sign-up')}>Создать аккаунт</button></div>}<form onSubmit={submit}>
    {mode!=='password'&&<label>Электронная почта<input name="email" type="email" autoComplete="email" placeholder="you@example.com" required maxLength={254}/></label>}
    {mode!=='reset'&&<label>Пароль<input name="password" type="password" autoComplete={mode==='sign-in'?'current-password':'new-password'} placeholder="Не менее 8 символов" minLength={8} maxLength={128} required/></label>}
    <ErrorBox text={error}/>{message&&<div className="notice" role="status">{message}</div>}
    <button className="primary wide" disabled={busy}>{busy?'Подождите…':mode==='sign-in'?'Войти в кабинет':mode==='sign-up'?'Создать аккаунт':mode==='reset'?'Отправить письмо':'Сохранить пароль'}<ArrowRight size={18}/></button>
    </form>{mode==='sign-in'&&<button className="text-button forgot" onClick={()=>choose('reset')}>Не помню пароль</button>}{mode==='reset'&&<button className="text-button forgot" onClick={()=>choose('sign-in')}>Вернуться ко входу</button>}<p className="auth-note"><ShieldCheck size={16}/> Пароль кабинета и родительский пароль в приложении задаются отдельно.</p></div><span className="auth-footer">Family Time · Время для важного</span></main></div>;
}

function UsageList({rows}:{rows:Usage[]}){
  const [expanded,setExpanded]=useState(false);const max=Math.max(1,...rows.map(r=>r.seconds));
  if(!rows.length)return <p className="muted padding">Пока нет записанной активности.</p>;
  return <><div className="usage-list">{rows.slice(0,expanded?rows.length:6).map(row=><div className="usage-row" key={row.key}><span className="app-symbol" style={{'--accent':categoryColor(row.category)} as CSSProperties}>{row.name.slice(0,1).toUpperCase()}</span><div className="usage-body"><div><span className="truncate" title={row.name}>{row.name}</span><strong>{duration(row.seconds)}</strong></div><div className="usage-track"><i style={{width:Math.max(1,row.seconds/max*100)+'%',background:categoryColor(row.category)}}/></div><small>{row.category}{row.key.startsWith('site:')?' · сайт':''}</small></div></div>)}</div>{rows.length>6&&<button className="text-button show-all" onClick={()=>setExpanded(!expanded)}>{expanded?'Свернуть':`Показать все (${rows.length})`}</button>}</>;
}
function Sessions({day,zone}:{day:DaySnapshot|undefined;zone:string}){
  if(!day)return <Empty title="Нет данных за этот день">Компьютер ещё не передал историю. После подключения она появится здесь.</Empty>;
  if(day.sessions===null)return <p className="muted padding">Дневные итоги сохранены. Подробные сеансы за этот день уже не хранятся в приложении.</p>;
  if(!day.sessions.length)return <p className="muted padding">Активных сеансов за этот день нет.</p>;
  return <div className="sessions">{day.sessions.map((s,i)=><details className="session" key={s.start}><summary><span className="session-dot"/><span><strong>{clock(s.start,zone)} <span className="muted">—</span> {clock(s.end,zone)}</strong><small>Сеанс {i+1} · {s.activities.length} {s.activities.length===1?'приложение или сайт':'приложений и сайтов'}</small></span><span className="session-duration">{duration(s.activeSeconds)} <ChevronRight size={17}/></span></summary><div className="session-inner"><UsageList rows={s.activities}/></div></details>)}</div>;
}
function WeekChart({data,onDay}:{data:DashboardData;onDay:(day:string)=>void}){
  const days=dayRange(data.from,data.to);const byDay=new Map(data.days.map(d=>[d.day,d]));
  const cats=combine(data.days.flatMap(d=>d.categories));const peak=Math.max(3600,...data.days.map(d=>d.activeSeconds));const scale=Math.ceil(peak/3600)*3600;
  return <><div className="chart" role="group" aria-label="Активное время по дням"><div className="chart-scale"><span>{duration(scale)}</span><span>{duration(scale/2)}</span><span>0</span></div><div className="chart-plot"><div className="chart-grid"/>{days.map((date,i)=>{const d=byDay.get(date);return <button key={date} className={'bar-column '+(date===data.today?'today':'')} onClick={()=>onDay(date)} title={`${dateLabel(date)}: ${d?duration(d.activeSeconds):'данных нет'}`} aria-label={`${dateLabel(date)}: ${d?duration(d.activeSeconds):'данных нет'}. Открыть историю.`}><span className="bar-space">{d?<span className="bar-stack" style={{height:Math.max(d.activeSeconds?1:0,d.activeSeconds/scale*100)+'%'}}>{d.categories.map(c=><i key={c.key} style={{height:c.seconds/Math.max(1,d.activeSeconds)*100+'%',background:categoryColor(c.name)}}/>)}</span>:<span className="missing-dot"/>}</span><small>{days.length<=7?new Intl.DateTimeFormat('ru',{weekday:'short',timeZone:'UTC'}).format(new Date(date+'T12:00Z')):i%5===0||i===days.length-1?date.slice(8):''}</small></button>;})}</div></div><div className="legend">{cats.map(c=><span key={c.key}><i style={{background:categoryColor(c.name)}}/>{c.name}</span>)}<span><i className="missing-legend"/>Нет данных</span></div></>;
}
function PairDialog({onClose,onRefresh}:{onClose:()=>void;onRefresh:()=>void}){
  const ref=useRef<HTMLDialogElement>(null);const [pair,setPair]=useState<{code:string;expiresAt:string}|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [copied,setCopied]=useState('');const [now,setNow]=useState(Date.now());
  useEffect(()=>{ref.current?.showModal();const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[]);
  async function create(){setBusy(true);setError('');try{setPair(await api('/api/devices','POST',{}));onRefresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function copy(value:string,which:string){try{await navigator.clipboard.writeText(value);setCopied(which);setTimeout(()=>setCopied(''),2000);}catch{setError('Выделите и скопируйте текст вручную.');}}
  const remaining=pair?Math.max(0,Math.ceil((Date.parse(pair.expiresAt)-now)/1000)):0;
  return <dialog ref={ref} className="pair-dialog" onCancel={onClose}><button className="icon-button close" onClick={onClose} aria-label="Закрыть"><X/></button><span className="empty-icon"><Monitor size={28}/></span><h2>Подключим компьютер</h2><p className="muted">Нужны приложение Family Time 0.2.0 или новее и доступ к интернету.</p><ol className="steps"><li><strong>Установите приложение</strong><p>На компьютере ребёнка. Существующие настройки сохранятся.</p><a className="download" href="https://github.com/nezamerznet-source/controltime/releases" target="_blank" rel="noreferrer"><ArrowDownToLine size={16}/> Скачать с GitHub</a></li><li><strong>Откройте настройки → Личный кабинет</strong><p>Скопируйте туда адрес этого кабинета:</p><div className="copy-field"><code>{typeof location!=='undefined'?location.origin:''}</code><button className="icon-button" aria-label="Скопировать адрес" onClick={()=>copy(location.origin,'url')}>{copied==='url'?<Check size={18}/>:<Copy size={18}/>}</button></div></li><li><strong>Введите одноразовый код</strong><p>Нажмите «Подключить» в приложении. Сохранившаяся история тоже будет загружена.</p>{pair&&remaining>0?<><div className="pair-code"><code>{pair.code}</code><button className="icon-button" aria-label="Скопировать код" onClick={()=>copy(pair.code,'code')}>{copied==='code'?<Check/>:<Copy/>}</button></div><small className="muted">Действует ещё {Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}. Не передавайте код посторонним.</small></>:<button className="primary" disabled={busy} onClick={create}>{busy?'Создаём…':pair?'Создать новый код':'Получить код подключения'}</button>}</li></ol><ErrorBox text={error}/><div className="privacy-note"><ShieldCheck size={18}/><span>Передаются время, названия программ и домены сайтов. Без снимков экрана, переписки и содержимого страниц.</span></div><button className="secondary wide" onClick={()=>{onRefresh();onClose();}}>Готово, проверить подключение</button></dialog>;
}

export default function Dashboard(){
  const [session,setSession]=useState<{configured:boolean;user:User|null}|null>(null);const [sessionError,setSessionError]=useState('');const [passwordMode,setPasswordMode]=useState(false);
  const [view,setView]=useState<View>('overview');const [period,setPeriod]=useState(7);const [date,setDate]=useState('');const [deviceId,setDeviceId]=useState('');const [data,setData]=useState<DashboardData|null>(null);
  const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [pairing,setPairing]=useState(false);const [deleting,setDeleting]=useState('');const requestNumber=useRef(0);
  const checkSession=useCallback(async()=>{try{setSessionError('');const s=await api<{configured:boolean;user:User|null}>('/api/session');setSession(s);setPasswordMode(new URLSearchParams(location.search).has('password'));}catch(e){setSessionError((e as Error).message);}},[]);
  useEffect(()=>{void checkSession();},[checkSession]);
  const load=useCallback(async()=>{
    if(!session?.user||passwordMode)return;
    const number=++requestNumber.current;setLoading(true);const q=new URLSearchParams();if(deviceId)q.set('device',deviceId);
    if(view==='history'&&date){q.set('from',date);q.set('to',date);}else if(data?.today&&period===30){q.set('from',shiftDay(data.today,-29));q.set('to',data.today);}
    try{const next=await api<DashboardData>('/api/dashboard?'+q);if(number===requestNumber.current){setData(next);setError('');}}
    catch(e){if(number===requestNumber.current)setError((e as Error).message);}finally{if(number===requestNumber.current)setLoading(false);}
  },[session?.user,passwordMode,deviceId,view,date,period,data?.today]);
  useEffect(()=>{void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},60_000);return()=>{clearInterval(timer);requestNumber.current++;};},[load]);
  async function logout(){try{await api('/api/auth','POST',{action:'sign-out'});setData(null);setDeviceId('');setDate('');await checkSession();}catch(e){setError((e as Error).message);}}
  async function remove(device:Device){if(!confirm(`Удалить «${device.name}» и всю его историю из кабинета? Доступ приложения будет отозван. Данные на компьютере сохранятся.`))return;setDeleting(device.id);try{await api('/api/devices/'+device.id,'DELETE');if(deviceId===device.id){setDeviceId('');}else void load();setData(null);}catch(e){setError((e as Error).message);}finally{setDeleting('');}}
  function navigate(next:View){if(next==='history'&&!date)setDate(data?.today??'');setView(next);}
  function historyDay(day:string){setDate(day);setView('history');}
  if(!session)return <div className="boot"><Brand/>{sessionError?<><ErrorBox text={sessionError}/><button className="secondary" onClick={checkSession}>Повторить</button></>:<p className="muted">Открываем кабинет…</p>}</div>;
  if(!session.configured)return <div className="boot"><Brand/><div className="panel setup"><Empty title="Кабинет готовится к запуску" icon={<Monitor/>}>Сервис входа и хранения истории ещё не подключён. После настройки он появится здесь автоматически.</Empty><button className="secondary" onClick={checkSession}>Проверить снова</button></div></div>;
  if(!session.user||passwordMode)return <Auth onLogin={()=>{setPasswordMode(false);void checkSession();}} passwordMode={passwordMode}/>;
  const selected=data?.devices.find(d=>d.id===data.selectedDeviceId);const zone=selected?.metadata.timeZone??'Europe/Moscow';const current=data?.days.find(d=>d.day===data.today);const chosen=data?.days.find(d=>d.day===(date||data.today));
  const categories=combine(data?.days.flatMap(d=>d.categories)??[]);const total=data?.days.reduce((n,d)=>n+d.activeSeconds,0)??0;const count=data?.days.length??0;
  const nav=[{key:'overview' as View,label:'Обзор',icon:LayoutDashboard},{key:'history' as View,label:'История',icon:CalendarDays},{key:'devices' as View,label:'Компьютеры',icon:Monitor}];
  return <div className="app-shell"><aside className="sidebar"><Brand/><span className="nav-caption">МОЯ СЕМЬЯ</span><nav aria-label="Основные разделы">{nav.map(n=><button key={n.key} className={view===n.key?'active':''} onClick={()=>navigate(n.key)} aria-current={view===n.key?'page':undefined}><n.icon size={20}/><span>{n.label}</span>{n.key==='devices'&&!!data?.devices.length&&<small>{data.devices.length}</small>}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-tip"><Smartphone size={23}/><strong>Всегда под рукой</strong><p>Откройте этот адрес на телефоне — история будет с вами.</p></div><div className="account"><span className="avatar">{session.user.email.slice(0,1).toUpperCase()}</span><div><strong>Личный кабинет</strong><small className="truncate" title={session.user.email}>{session.user.email}</small></div><button className="icon-button" onClick={logout} aria-label="Выйти из аккаунта"><LogOut size={17}/></button></div></div></aside>
  <main className="workspace"><header className="topbar"><div className="mobile-brand"><Brand/></div><span className="desktop-greeting">Ваш семейный обзор</span><div className="topbar-actions">{data&&data.devices.length>0&&<label className="device-select"><Monitor size={17}/><select aria-label="Выбрать компьютер" value={data.selectedDeviceId??''} onChange={e=>{setDeviceId(e.target.value);setDate('');setData(null);}}>{data.devices.map(d=><option key={d.id} value={d.id}>{d.metadata.profileName??d.name}</option>)}</select></label>}<button className={'icon-button '+(loading?'spinning':'')} disabled={loading} onClick={load} aria-label="Обновить данные"><RefreshCw size={18}/></button><button className="icon-button mobile-logout" onClick={logout} aria-label="Выйти из аккаунта"><LogOut size={18}/></button></div></header>
  <div className="page-content"><div className="page-title"><div><span className="eyebrow">{view==='overview'?'ВРЕМЯ ДЛЯ БАЛАНСА':view==='history'?'КАЖДЫЙ ДЕНЬ В ДЕТАЛЯХ':'НА СВЯЗИ С СЕМЬЁЙ'}</span><h1>{view==='overview'?'Как проходит день':view==='history'?'История активности':'Ваши компьютеры'}</h1><p>{view==='overview'?`${selected?.metadata.profileName??'Ваша семья'} · ${data?dateLabel(data.today):'Загружаем данные'}`:view==='history'?'Приложения, сайты и сеансы — всё по порядку.':'Подключение и состояние синхронизации.'}</p></div>{view==='devices'?<button className="primary" onClick={()=>setPairing(true)}><Plus size={18}/> Подключить компьютер</button>:selected&&<Status device={selected}/>}</div>
  <ErrorBox text={error}/>{loading&&!data&&<div className="panel loading" role="status">Загружаем вашу историю…</div>}
  {data&&!data.devices.length&&view!=='devices'&&<div className="panel welcome"><Empty title="Начнём с вашего компьютера" icon={<Monitor size={36}/>}>Подключите Family Time, и здесь появятся время за компьютером, любимые приложения и история.<br/><button className="primary" onClick={()=>setPairing(true)}><Plus size={18}/> Подключить компьютер</button></Empty><div className="welcome-features"><span><Activity/> Точное активное время</span><span><CalendarDays/> История, даже без связи</span><span><ShieldCheck/> Отдельный кабинет семьи</span></div></div>}
  {selected&&data&&view==='overview'&&<>
    {!online(selected)&&<div className="connection-note"><WifiOff size={18}/><span>Компьютер сейчас не на связи. История доступна по последней синхронизации: <strong>{stamp(selected.last_seen_at,zone)}</strong>.</span><Help text="Нет связи может означать, что компьютер выключен, спит, приложение закрыто или нет интернета. Новая история загрузится после восстановления связи."/></div>}
    <div className="hero-grid"><section className="panel today-card"><div><div className="card-kicker"><Clock3 size={17}/> Сегодня за компьютером <Help text="Активное время: работа с клавиатурой и мышью, а также видео на переднем плане. Простой и фоновое видео показаны отдельно."/></div><div className="big-time">{current?duration(current.activeSeconds):'Пока нет данных'}</div><p>{current?selected.metadata.paused?'Учёт сейчас приостановлен':'Активное время за сегодняшний день':'Ожидаем первую синхронизацию за сегодня'}</p><div className="today-foot"><span><i className="mini-dot"/> Последние данные</span><strong>{stamp(selected.metadata.lastObservedAt??null,zone)}</strong></div></div><div className="time-ring" style={{'--progress':`${current&&selected.metadata.limitEnabled?Math.min(100,current.activeSeconds/((selected.metadata.limitMinutes??120)*60)*100):0}%`} as CSSProperties}><Clock3 size={37} strokeWidth={1.5}/><small>сегодня</small></div></section>
    <section className="panel budget-card"><span className="card-kicker">Дневной ориентир <Help text="Лимит задаётся в приложении на компьютере. Кабинет показывает последний полученный лимит; он не блокирует компьютер."/></span><h2>{!selected.metadata.limitEnabled?'Без лимита':current?duration(Math.max(0,(selected.metadata.limitMinutes??120)*60-current.activeSeconds)):'—'}</h2><p>{selected.metadata.limitEnabled?'осталось из '+duration((selected.metadata.limitMinutes??120)*60):'Можно задать в настройках приложения'}</p><div className="budget-track"><i style={{width:current&&selected.metadata.limitEnabled?Math.min(100,current.activeSeconds/((selected.metadata.limitMinutes??120)*60)*100)+'%':'0%'}}/></div><small>{selected.metadata.limitEnabled&&current&&current.activeSeconds>(selected.metadata.limitMinutes??120)*60?'Сверх ориентира: '+duration(current.activeSeconds-(selected.metadata.limitMinutes??120)*60):'Баланс начинается с понимания привычек'}</small></section></div>
    <section className="panel chart-card"><div className="section-heading"><div><h2>Ритм недели <Help text="Нажмите на столбик, чтобы открыть день. Точка вместо столбика означает отсутствие данных, а не нулевое использование."/></h2><p>{dateLabel(data.from,true)} — {dateLabel(data.to,true)}</p></div><div className="segmented"><button className={period===7?'selected':''} onClick={()=>setPeriod(7)}>7 дней</button><button className={period===30?'selected':''} onClick={()=>setPeriod(30)}>30 дней</button></div></div><div className="chart-summary"><strong>{duration(total)}</strong><span>за период</span><i/><strong>{count?duration(total/count):'—'}</strong><span>в среднем за день с данными</span></div><WeekChart data={data} onDay={historyDay}/></section>
    <div className="category-grid">{(categories.length?categories:[{key:'study',name:'Учёба',seconds:0},{key:'games',name:'Игры',seconds:0},{key:'video',name:'Видео',seconds:0},{key:'other',name:'Другое',seconds:0}]).slice(0,4).map(c=><div className="panel category-card" key={c.key}><span><i style={{background:categoryColor(c.name)}}/>{c.name}</span><strong>{count?duration(c.seconds):'—'}</strong><small>за выбранный период</small></div>)}</div>
    <div className="details-grid"><section className="panel"><div className="section-heading"><div><h2>Приложения и сайты</h2><p>За выбранный период</p></div><Help text="Сайты отображаются после подключения расширения Chrome или Edge. Без расширения видно общее время браузера. Категории можно изменить в приложении."/></div><UsageList rows={activities(data.days)}/></section><section className="panel"><div className="section-heading"><div><h2>Сегодня по сеансам</h2><p>Активность между перерывами</p></div><button className="text-button" onClick={()=>historyDay(data.today)}>Вся история <ArrowRight size={15}/></button></div><Sessions day={current} zone={zone}/></section></div>
  </>}
  {selected&&data&&view==='history'&&<><section className="panel history-controls"><div className="date-navigation"><button className="icon-button" aria-label="Предыдущий день" onClick={()=>setDate(shiftDay(date||data.today,-1))}><ChevronLeft/></button><label><CalendarDays size={19}/><input type="date" aria-label="Дата истории" value={date||data.today} max={data.today} onChange={e=>e.target.value&&setDate(e.target.value)}/></label><button className="icon-button" aria-label="Следующий день" disabled={(date||data.today)>=data.today} onClick={()=>setDate(shiftDay(date||data.today,1))}><ChevronRight/></button></div><button className="text-button" onClick={()=>setDate(data.today)}>Сегодня</button><span className="history-total">{chosen?duration(chosen.activeSeconds):'Нет данных'} <small>активного времени</small></span></section>{chosen&&<div className="history-facts"><span>Простой: <strong>{duration(chosen.idleSeconds)}</strong></span><span>Учёт не работал: <strong>{duration(chosen.unknownSeconds)}</strong></span><span>Фоновое видео: <strong>{duration(chosen.backgroundSeconds)}</strong><Help text="Фоновое видео не прибавляется к активному времени. Неучтённые промежутки могут включать паузу, выключенный компьютер или неработавшее приложение."/></span></div>}<div className="details-grid history-grid"><section className="panel"><div className="section-heading"><div><h2>Сеансы за {dateLabel(date||data.today)}</h2><p>Время в часовом поясе компьютера · {zone}</p></div></div><Sessions day={chosen} zone={zone}/></section><section className="panel"><div className="section-heading"><h2>Чем был занят день</h2></div><UsageList rows={chosen?.activities??[]}/>{!!chosen?.browserUnknownSeconds&&<div className="soft-note">Без детализации сайтов: {duration(chosen.browserUnknownSeconds)}. Проверьте расширение браузера в приложении.</div>}</section></div></>}
  {data&&view==='devices'&&<><div className="devices-grid">{data.devices.map(d=><section className="panel device-card" key={d.id}><div className="device-top"><span className="empty-icon"><Monitor size={28}/></span><Status device={d}/></div><h2>{d.metadata.profileName??d.name}</h2><p className="muted truncate" title={d.name}>{d.name}</p><dl><div><dt>Последняя синхронизация</dt><dd>{stamp(d.last_seen_at,d.metadata.timeZone)}</dd></div><div><dt>Последнее наблюдение</dt><dd>{stamp(d.metadata.lastObservedAt??null,d.metadata.timeZone)}</dd></div><div><dt>Расширение браузера</dt><dd>{d.last_seen_at?d.metadata.browserConnected?'Было подключено':'Не было связи':'Ожидаем данные'}</dd></div><div><dt>История / итоги</dt><dd>{d.metadata.historyDays??'—'} / {d.metadata.summaryDays??'—'} дней</dd></div></dl><div className="device-actions"><button className="text-button" onClick={()=>{setDeviceId(d.id);setDate('');setView('overview');setData(null);}}>Открыть обзор <ArrowRight size={16}/></button><button className="icon-button danger" disabled={!!deleting} onClick={()=>remove(d)} aria-label={'Удалить компьютер '+d.name}><Trash2 size={17}/></button></div></section>)}<button className="add-device" onClick={()=>setPairing(true)}><span><Plus size={27}/></span><strong>Ещё один компьютер</strong><small>Подключите по одноразовому коду</small></button></div><div className="privacy-note device-privacy"><ShieldCheck size={22}/><div><strong>Ваши данные остаются в вашей семье</strong><p>Пароль аккаунта не хранится на компьютере ребёнка. Удаление компьютера здесь отзывает его доступ и удаляет его облачную историю. Локальная история в приложении остаётся.</p></div></div></>}
  {selected&&<footer className="page-footer"><span><ShieldCheck size={14}/> Видно только вашей семье</span><span>Часовой пояс: {zone}</span></footer>}
  </div></main><nav className="bottom-nav" aria-label="Разделы на телефоне">{nav.map(n=><button key={n.key} className={view===n.key?'active':''} onClick={()=>navigate(n.key)}><n.icon size={21}/>{n.label}</button>)}</nav>{pairing&&<PairDialog onClose={()=>setPairing(false)} onRefresh={load}/>}</div>;
}
